In [30]:


import pandas as pd
import csv
import pymysql
import time
from machine129 import meals

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [17]:
try:
    conn = pymysql.connect(user='root', passwd='1234', host='34.64.136.121', db='mydb129', charset='utf8')
    print('===접속 성공===')
    cursor = conn.cursor(pymysql.cursors.DictCursor) # pandas dataframe 형태로 받아오는 커서
except pymysql.DatabaseError as db_err:
    print('접속 오류 !!')
    print(db_err)

===접속 성공===

In [18]:
query = 'CREATE TABLE IF NOT EXISTS users (\
    user_id varchar(50) primary key,\
    user_pw varchar(50),\
    phone_number varchar(50)\
    )'

cur=conn.cursor()
try:
    cur.execute(query)
    conn.commit()
except:
    print('Error!')

In [33]:
%load_ext autoreload
%autoreload 2

from machine129 import meals

db = meals.meals()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [34]:
db.select_query('SELECT * FROM Food')

,class_num,food_name,serving_size_g,calorie_kJ,calorie_kcal,carbohydrate_g,sugar_g,protein_g,fat_g,saturated_fat_g,polyunsaturated_fat_g,unsaturated_fat_g,cholesterol_mg,dietary_fiber_g,salt_mg,potassium_mg
0,0,잡곡밥,200.0,1424.0,340.0,73.47,0.10,8.82,1.98,0.342,0.793,0.565,0.0,3.9,273.0,208.0
1,1,배추김치,38.0,35.0,8.0,1.58,0.70,0.66,0.12,0.018,0.056,0.017,0.0,0.5,245.0,98.0
2,2,된장찌개,200.0,717.0,171.0,16.77,3.80,15.01,5.60,1.034,2.455,1.463,21.0,3.2,682.0,613.0
3,3,김치찌개,200.0,505.0,121.0,6.47,1.77,7.51,7.57,1.903,2.129,2.935,15.0,1.4,442.0,330.0
4,4,멸치볶음,40.0,289.0,69.0,0.35,0.08,7.43,4.09,0.784,1.105,1.840,21.0,0.1,1022.0,147.0
5,5,시금치나물,100.0,286.0,68.0,7.35,0.97,3.27,3.67,0.526,1.568,1.348,0.0,2.6,593.0,403.0
6,6,가지나물,165.0,297.0,71.0,11.02,3.39,2.97,2.95,0.451,1.301,0.920,0.0,5.8,261.0,397.0
7,7,고사리나물,80.0,214.0,51.0,5.50,1.43,2.60,2.71,0.363,1.097,0.987,0.0,0.5,142.0,175.0
8,8,미역국,230.0,346.0,83.0,5.59,0.62,7.87,3.73,0.975,1.099,1.240,14.0,0.5,1134.0,223.0
9,9,김밥,125.0,611.0,148.0,32.03,5.54,2.72,0.29,0.081,0.086,0.086,0.0,0.5,119.0,76.0
10,10,불고기,300.0,2034.0,486.0,14.77,7.17,48.38,23.86,6.068,5.905,9.603,103.0,2.6,583.0,853.0
11,11,호박볶음,75.0,375.0,90.0,5.24,1.27,1.20,7.68,1.092,3.231,3.007,0.0,1.4,374.0,177.0
12,12,무생채,200.0,333.0,80.0,14.34,8.06,2.30,2.28,0.364,1.007,0.745,0.0,4.5,1383.0,490.0
13,13,잡채,150.0,1194.0,285.0,43.23,3.03,7.59,10.16,1.437,4.626,3.475,0.0,3.4,808.0,341.0
14,14,무국,200.0,503.0,120.0,13.78,4.03,2.75,6.65,0.980,2.773,2.575,0.0,3.5,1088.0,603.0
15,15,고등어구이,200.0,1586.0,379.0,0.70,0.18,35.18,25.19,5.809,6.841,9.569,120.0,0.0,822.0,693.0
16,16,쌀밥,210.0,1130.0,270.0,61.00,0.00,5.00,0.70,0.000,0.000,0.000,0.0,0.0,20.0,0.0
17,17,계란후라이,46.0,373.0,89.0,0.43,0.38,6.24,6.76,1.880,1.214,2.754,210.0,0.0,238.0,67.0
18,18,계란말이,250.0,1407.0,336.0,6.53,2.81,25.46,22.40,6.181,3.641,9.217,808.0,1.6,772.0,415.0

In [35]:
db.label_to_meals(id = 'testid0606@gmail.com')

yogijogi Error!

UnboundLocalError: local variable 'score' referenced before assignment

In [37]:
path="D:\Final_Project\Git_repositories\Main\static\detect\exp\labels\image1.txt"
id="testid0606@gmail.com"

with open(path, 'r') as f:
    data = f.readlines()

label_num_list = []
for a in data:
    label_num_list.append(int(a.split(' ')[0]))


# Query 만들기
# Select "요기" FROM "조기"
cur = conn.cursor()
try:
    cur.execute("Select COLUMN_NAME From INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Food' and data_type = 'float' order by ordinal_position;")
    fcolumns = cur.fetchall()
except:
    print('M129 Query Make Error')

## "요기"
columns_query = ''
for i in fcolumns:
    columns_query += 'sum(' + i[0] + '), '
columns_query = columns_query.rstrip(', ')

## "조기"
label_list = list(set(label_num_list)) # list > set > list 를 통해 중복값을 제거 해줌.
where_query = ''
for i in label_list:
    where_query += 'class_num = ' + str(i) + " or "
where_query = where_query.rstrip(' or ')

query = 'SELECT ' + columns_query + ' FROM food WHERE ' + where_query

query
# cur=conn.cursor()
# try:
#     cur.execute(query)
#     score = cur.fetchall() # score = meals 영양소
# except:
#     print('yogijogi Error!')

'SELECT sum(serving_size_g), sum(calorie_kJ), sum(calorie_kcal), sum(carbohydrate_g), sum(sugar_g), sum(protein_g), sum(fat_g), sum(saturated_fat_g), sum(polyunsaturated_fat_g), sum(unsaturated_fat_g), sum(cholesterol_mg), sum(dietary_fiber_g), sum(salt_mg), sum(potassium_mg) FROM food WHERE class_num = 16 or class_num = 6'

In [38]:
db.select_query('SELECT * FROM meals')

,user_id,date_time,serving_size_g,calorie_kJ,calorie_kcal,carbohydrate_g,sugar_g,protein_g,fat_g,saturated_fat_g,polyunsaturated_fat_g,unsaturated_fat_g,cholesterol_mg,dietary_fiber_g,salt_mg,potassium_mg
0,testemail@gmail.com,2022-05-31 14:45:13,520.0,1690.0,404.0,72.09,2.05,15.47,7.14,1.338,2.196,2.227,14.0,1.0,1296.0,398.0